GYFE backend
metakgp/gyfe pull request #18
Opened 2024-06-14 14:03 UTC by premagarwals

2024-06-28 16:34 UTC, rohan-b-84 requested changes

2024-06-28 16:34 UTC, rohan-b-84 commented on app.py
> +jwt_secret_key :str = "secret-key"
Put `jwt_secret_key` as an environment variable !!

2024-06-28 16:34 UTC, rohan-b-84 commented on app.py
> +
I think all this can also be computed and set to a default value using roll number and the current date/time
like dept, year from roll number
session, semester from date
electives can be URL param

Eg:
`/elective/breadth`
`/elective/depth`

2024-06-28 16:34 UTC, rohan-b-84 commented on app.py
> +
@proffapt @ashwinpra  thoughts ?

2024-06-28 16:34 UTC, rohan-b-84 commented on app.py
> +        response = (response_1, response_2, response_3)
what ??

2024-06-28 16:34 UTC, rohan-b-84 commented on gyfe.py
> +        core_courses = response.json()
do `response.json()` outside this function.
Pass the `core_courses` json into function

2024-06-28 16:46 UTC, premagarwals commented on app.py
> +        response = (response_1, response_2, response_3)
save_depth and save_breadth each fetches data 2 times that is passed through response_1 and response_2, moreover, they call find_core_courses which also fetches data that is response_3. If we don't provide them these 3 responses, they will need to fetch the data themselves, and un logo ke liye alag se login ka Funda create hoga. So, either 3no response fetch krke provide krna hoga ya koi sa bhi nhi.

2024-06-28 16:49 UTC, premagarwals commented on gyfe.py
> +        core_courses = response.json()
find_core_courses is called by save_depth and save_breadth. So, function k bahar calculate krna matlab save_depth ya save_breadth me response ko handle krke this function ko pass krna. Ab agar error handling k sath pass kre toh save_depth and save_breadth dono me same code likhna hoga...maine socha usse achha ek hi baar isi function me kaam ho jaye.

2024-06-28 16:56 UTC, proffapt commented on requirements.txt
> +iitkgp_erp_login==2.4.0
```suggestion
iitkgp_erp_login==2.4.1
```

2024-06-28 16:56 UTC, proffapt commented on app.py
> +
yes, the idea is there in gyft, @ashwinpra implemented it.

2024-06-28 16:56 UTC, proffapt commented on app.py
> +        }
Already defined in global variable

2024-06-28 16:56 UTC, proffapt commented on app.py
> +        response = (response_1, response_2, response_3)
Have a decent naming convention to tell what all those responses are.

2024-06-28 16:56 UTC, proffapt commented on app.py
> +
```suggestion
```

2024-06-28 16:56 UTC, proffapt commented on app.py
> +
```suggestion
```

2024-06-28 16:56 UTC, proffapt commented on app.py
> +
```suggestion
```

2024-06-28 16:56 UTC, proffapt commented on gyfe.py
why are things being passed or set as none after try statements all over the file?

2024-06-28 17:07 UTC, premagarwals commented on gyfe.py
These aren't completed error handling. The thing is ki saare error throw kr dete h due to a major assumption ki list empty nhi ho sakti. So, kahi par None object pr find_all use ho jaa rha kahi empty list ki index 1 ko fetch kr rhe, so atlast assignees ko "None" hi hona h, so maine except me unhe None kr diya h. Filhaal aisa krne se program ke random crashes stop ho gaye h. Maine sirf unhi locations pr implement Kiya h jaha jaha error aa chuke h. I will have to make it more specific though.

2024-06-28 17:58 UTC, proffapt commented on gyfe.py
I see, so what happens when they are set to none? it doesn't throw error and it won't be included so is that a problem or not?

2024-06-28 18:33 UTC, premagarwals commented on gyfe.py
Actually I don't have any idea what values to give them if there doesn't exist any meaningful value. They are basically void.

2024-06-28 19:12 UTC, proffapt commented on gyfe.py
umm hmm ok

2024-07-02 14:45 UTC, rohan-b-84 requested changes

2024-07-02 14:45 UTC, rohan-b-84 commented on app.py
> +jwt_secret_key = app.config['JWT_SECRET_KEY']
```suggestion
jwt_secret_key = os.getenv('JWT_SECRET_KEY')

if not jwt_secret_key:
    raise ValueError("No JWT_SECRET_KEY set for Flask application")
```

2024-07-02 14:45 UTC, rohan-b-84 commented on app.py
> +        YEAR = int(ROLL_NUMBER[1])
> YEAR = int(ROLL_NUMBER[1])

what? how would this work in future without intervention ?

2024-07-02 14:45 UTC, rohan-b-84 commented on app.py
> +            PRIMARY_RESP = session_manager.request(jwt=jwt, method='GET', url=ERP_ELECTIVES_URL, headers=headers)
```suggestion
            ERP_ELECTIVES_RESP = session_manager.request(jwt=jwt, method='GET', url=ERP_ELECTIVES_URL, headers=headers)
```

2024-07-02 14:45 UTC, rohan-b-84 commented on app.py
> +        response = (PRIMARY_RESP, SUBJ_LIST_RESP, COURSES_RESP)
```suggestion
        response = (ERP_ELECTIVES_RESP, SUBJ_LIST_RESP, COURSES_RESP) 
```

2024-07-10 20:52 UTC, merged